# Generated by Django 6.0.7 on 2026-07-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('ADMIN', 'Administrator')], default='STUDENT', max_length=20),
        ),
    ]
